// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsDK6iWdd44Nvypjj8AHUKQyJW6JX1uuI',
    appId: '1:988620818401:web:dfde26d9ce176197bd74a0',
    messagingSenderId: '988620818401',
    projectId: 'finance-project-45d87',
    authDomain: 'finance-project-45d87.firebaseapp.com',
    storageBucket: 'finance-project-45d87.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFqMSan6anPD0HzvijzPusKOqgRuCBEfs',
    appId: '1:988620818401:android:a756112a4b797e82bd74a0',
    messagingSenderId: '988620818401',
    projectId: 'finance-project-45d87',
    storageBucket: 'finance-project-45d87.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9aibRJqpeYNryECz4ioumXEGc7ZGJdc8',
    appId: '1:988620818401:ios:1750a4b17e09c38cbd74a0',
    messagingSenderId: '988620818401',
    projectId: 'finance-project-45d87',
    storageBucket: 'finance-project-45d87.appspot.com',
    iosClientId: '988620818401-e8hv8vbfqn3fgfchdn8od2j40k863bti.apps.googleusercontent.com',
    iosBundleId: 'com.example.financeProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9aibRJqpeYNryECz4ioumXEGc7ZGJdc8',
    appId: '1:988620818401:ios:1750a4b17e09c38cbd74a0',
    messagingSenderId: '988620818401',
    projectId: 'finance-project-45d87',
    storageBucket: 'finance-project-45d87.appspot.com',
    iosClientId: '988620818401-e8hv8vbfqn3fgfchdn8od2j40k863bti.apps.googleusercontent.com',
    iosBundleId: 'com.example.financeProject',
  );
}
